import glob
import os 
import numpy as np 
import pandas as pd 
from SR.spectral_residual import Silency

if __name__=="__main__":
    files = glob.glob('../dataset/kpi/train/*.csv')
    for file in files:
        # save file in ../dataset/kpi/sr-vae/
        os.makedirs('../dataset/kpi/sr-vae', exist_ok=True)
        save_path = file.replace('../dataset/kpi/train', '../dataset/kpi/sr-vae')

        df = pd.read_csv(file)
        timestamp = df["timestamp"].values 
        value = df["value"].values  

        spec = Silency(amp_window_size=3, series_window_size=3, score_window_size=5)
        sr = spec.transform_spectral_residual(value)
        threshold = np.percentile(sr, 97.5)
        # pred represents the label generated by employing the SR algorithm
        pred = np.array([1.0 if sr[i] > threshold else 0.0 for i in range(0, len(sr))])

        df.loc[:,"pred"] = pred
        # df1 = df[df.label<2.0] # remove missing values
        df.to_csv(save_path, index=None) # type: ignore
